version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-php
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: movies-nginx
    working_dir: /application
    depends_on:
      - php
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/mysql/data
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    container_name: mysql
    working_dir: /mysql/data
    command: "--init-file /data/application/init.sql"
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stake_limit_service
    ports:
      - "3306:3306"

  composer:
    image: composer/composer
    ports:
      - "9001:9000"
    depends_on:
      - php
    volumes:
      - .:/application
    working_dir: /application
    container_name: composer
    command: install

volumes:
  mysql-data: